language: python
sudo: false
cache: apt
addons:
    apt:
        sources:
        - llvm-toolchain-precise
        - ubuntu-toolchain-r-test
        packages:
        # OpenCL
        - clang-3.4
        - cmake
        - g++-5
        - hwloc
        - libclang-3.4-dev
        - libedit-dev
        - libgl1-mesa-dev
        - libhwloc-dev
        - libltdl-dev
        - llvm-3.4-dev
        - pkg-config
        # Docs
        - python-docutils
        - python-matplotlib
        - python-sphinx
env:
    global:
        - LD_LIBRARY_PATH=$HOME/opt/pocl/lib
        - TOX_TESTENV_PASSENV=LD_LIBRARY_PATH
    matrix:
        - TOX_ENV=py34
        - TOX_ENV=py27
        - TOX_ENV=py34-opencl
        - TOX_ENV=py27-opencl
        - TOX_ENV=docs
install:
    - pip install --upgrade pip
    - pip install tox coveralls
    - scripts/travis-install.sh
script:
    - tox -e $TOX_ENV
after_success:
    - coveralls

# vim:sw=4:sts=4:et:ts=4
