language: python
sudo: false
env:
    - TOX_ENV=py34
    - TOX_ENV=py27
    - TOX_ENV=py34-opencl
    - TOX_ENV=py27-opencl
    - TOX_ENV=docs
install:
    - pip install --upgrade pip
    - pip install tox coveralls
script:
    - tox -e $TOX_ENV
after_success:
    - coveralls

